apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: wallclocks-rbac-hack
subjects:
  - kind: ServiceAccount
    name: default
    namespace: wallclocks-system 
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
